name = "flash-royale"
main = ".open-next/worker.js"

compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

minify = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "flash-royale-db"
database_id = "68ccf195-5e42-40bf-a166-7a9b62387899"

[[r2_buckets]]
bucket_name = "flash-royale-cache"
binding = "NEXT_INC_CACHE_R2_BUCKET"